image:
  name: hashicorp/terraform:light
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
    - 'AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}' 
    - 'AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}' 
    - 'AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}'

variables:
  PLAN: plan.tfplan

cache:
  paths:
    - .terraform

before_script:
  - rm -rf .terraform
  - terraform --version
  - terraform init

stages:
  - test
  - plan
  - apply
  - destroy

validate:
  stage: test
  script:
    - terraform validate
 
build:
  stage: plan
  script:
    - terraform plan -lock=false -out=$PLAN
  artifacts:
    name: plan
    paths:
      - $PLAN

apply:
  stage: apply
  rules:
      - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

  script:
    - terraform apply -input=false $PLAN
  dependencies:
    - build
  when: manual

destroy:
  stage: destroy
  rules:
      - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - echo "Destroying all resources .. "
    - terraform destroy -state=$STATE --auto-approve
  dependencies:
    - apply  
  when: manual
