# https://www.cloudytuts.com/tutorials/kubernetes/how-to-base64-encode-kubernetes-secrets/
apiVersion: v1
kind: Secret
metadata:
  name: elasticsearch-secret
  namespace: logging
data:
  CLOUD_ELASTICSEARCH_PASSWORD: ZHVQNG0wQmtHYzZyUElCZUxxdjMwT2JJ
  CLOUD_ELASTICSEARCH_USER: ZWxhc3RpYw==
type: Opaque
